# Generated by Django 2.0.6 on 2018-07-07 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180620_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 14, 51, 40, 150445, tzinfo=utc)),
        ),
    ]
