# Generated by Django 2.0.6 on 2018-07-10 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180710_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 10, 13, 37, 31, 729918, tzinfo=utc)),
        ),
    ]
