# Generated by Django 2.0.6 on 2018-07-11 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20180710_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 12, 57, 18, 88325, tzinfo=utc)),
        ),
    ]
