# Generated by Django 2.0.6 on 2019-10-19 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20190408_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 8, 53, 50, 623200, tzinfo=utc)),
        ),
    ]
