# Generated by Django 2.0.6 on 2019-10-20 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20191019_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 7, 49, 27, 247672, tzinfo=utc)),
        ),
    ]
